export const FETCH_CAPSULES_REQUEST = 'FETCH_CAPSULES_REQUEST';
export const FETCH_CAPSULES_SUCCESS = 'FETCH_CAPSULES_SUCCESS';
export const FETCH_CAPSULES_FAILURE = 'FETCH_CAPSULES_FAILURE';
export const FILTER_CAPSULES = 'FILTER_CAPSULES';
export const PAGINATE_CAPSULES = 'PAGINATE_CAPSULES';
